name: Secrets Check

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Detect secrets in incoming commits with Talisman
        uses: carhartl/talisman-secrets-scan-action@v1.0
